### ISSUE TITLE
VCF-miner timeout

### ISSUE THREAD

**Issue by psddia** [Steven-N-Hart/vcf-miner#15]
I'm loading a large CVF file and every time my computer goes to screensaver or I logout, VCF-miner times out. Is there a way to prevent this? Also, how do I save my uploaded VCF files so that I don't have to reload them every time?

**Comment by psddia** [comment]
I'm also getting an error of "ran out of memory". How do I increase the size?

**Comment by Steven-N-Hart** [comment]
What is the vcf file size and what are your computer specs?

**Comment by psddia** [comment]
Huge, 4.7gb in the .gz compressed file which turns into 39gb uncompressed. I have an i7 with 16gb ram. Do I need to run it on the cluster? Does vcfminer use all available cores and ram as defualt?

**Comment by Steven-N-Hart** [comment]
I've got a message out to one of my colleagues, but it sounds like the file is too big for your machine.

**Comment by psddia** [comment]
As I've looked at the container messages in kinematic, I think it is a pure memory problem. But, I've downloaded the 3 smallest files from 1000genomes and only the mitochondria and Y file will load. The chromosome 22 file errors. And that file is only ~200MB.

How can I check to see what size RAM is allocated to Miner?

**Comment by psddia** [comment]
https://i.imgur.com/9CvMzm4.png

then this...

https://i.imgur.com/B8DI8bq.png
it happened at 70%
https://i.imgur.com/eBW4Aym.png

kitematic says "failed to write...no space left on device"
https://i.imgur.com/w2j35n2.png

**Comment by Steven-N-Hart** [comment]
Ok. This explains it. Your hard drive is too full, so you can't create the database.  No database,  no app.  You need a larger hard drive or freeup more space.
