### ISSUE TITLE
vcf-miner with ped files?

### ISSUE THREAD

**Issue by ramaniak** [Steven-N-Hart/vcf-miner#2]
Hello,
If I understand correctly, vcf-miner does not utilize pedigree information to filter for variants. Is this correct? If so, is there any development in progress that would see this implemented in future releases?

thanks very much
Arun

**Comment by Steven-N-Hart** [comment]
Arun,
Can you describe the feature a little bit more that you are requesting?  You should be allowed to filter by different combinations of samples - even without a PED file.

**Comment by ramaniak** [comment]
Hello Steven,
Thanks for your quick response. I am looking to carry out analysis with
trios: denovo calling, compound heterozygotes and such. Is there a way to
carry this out in the current release?

thanks

**Comment by Steven-N-Hart** [comment]
Yes.  
To get de novo:
create a group for the parents And 1 for the Child.
In the Custom Tab of the filter modal, select "Variants NOT IN Group", with the "Either" radio button selected where the value = "Parents".  This removes any variant found in mom OR dad - hence de novo.

For compound het, select "Variants IN Group" = "Parent", but this time select heterozygous.  Next add another filter where "Variants IN Group" = "Child" and set the genotype to "Heterozygous".  Now, to get true compound hets - assuming neither parent has the disease, you would further select " "Variants NOT IN Group" = "Parent" but select "Homozygous" (remove variants that are homozygous in either parent)

Make sense?

**Comment by ramaniak** [comment]
Yes, makes sense. Let me try it out and let you know of I run into any
difficulties.

Cheers
Arun
