### ISSUE TITLE
Install issues accessing nexus.mayo.edu

### ISSUE THREAD

**Issue by colindaven** [Steven-N-Hart/vcf-miner#4]
Hi,

thanks for your help in the other issue with the docker instance. Unfortunately that did not solve my problem, as the docker build step repeatedly failed.

I then tried the manual approach on a bare metal ubuntu 16.04 server.

This went quite well, I found the settings.xml and installed the maven proxy without issues.

However only two WAR files were created. The third failed with this message:

`[ERROR] Failed to execute goal on project mongo_svr: Could not resolve dependencies for project edu.mayo.mongo_svr:mongo_svr:war:4.0
.3: Failed to collect dependencies at edu.mayo:mayo-commons-mongodb:jar:3.0.9: Failed to read artifact descriptor for edu.mayo:mayo-
commons-mongodb:jar:3.0.9: Could not transfer artifact edu.mayo:mayo-commons-parent:pom:0.0.5 from/to mayo-nexus (http://nexus.mayo.
edu/content/groups/public/): Failed to transfer file: http://nexus.mayo.edu/content/groups/public/edu/mayo/mayo-commons-parent/0.0.5
/mayo-commons-parent-0.0.5.pom. Return code is: 502 , ReasonPhrase:No route to host. -> [Help 1]`

Any ideas, i.e. server down? I could not access the server via web browser or wget either.

Thanks,
Colin

**Comment by Steven-N-Hart** [comment]
What commit are you using?

**Comment by colindaven** [comment]
This might well have been due to network issues my end, so no sense trying to solve this at present. Will try again and comment again if I can reproduce. Thanks.

**Comment by Steven-N-Hart** [comment]
Try now.  I updated the install procedures.
