### ISSUE TITLE
Potential Proxy not detected issue - docker version

### ISSUE THREAD

**Issue by colindaven** [Steven-N-Hart/vcf-miner#5]
Hi, just retried on the current git commit.

It seems the proxy is not being picked up.

docker build -t vcfminer . 
[sudo] password for rcug: 
Sending build context to Docker daemon 370.1 MB
Step 1 : FROM centos:6
6: Pulling from library/centos
32c4f4fef1c6: Already exists 
Digest: sha256:1092df198d3da4faccc0660941b763ce5adf133b0ec71701b760d6f173c1f47b
Status: Downloaded newer image for centos:6
 ---> 8315978ceaaa
Step 2 : MAINTAINER Steven N Hart, PhD
 ---> Running in 93c3eea3d9dd
 ---> 0f97d17393bc
Removing intermediate container 93c3eea3d9dd
Step 3 : RUN yum install -y java-1.7.0-openjdk.x86_64 java-1.7.0-openjdk-devel wget tar
 ---> Running in bdb5cdea1ce8
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os&infra=container error was
14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
The command '/bin/sh -c yum install -y java-1.7.0-openjdk.x86_64 java-1.7.0-openjdk-devel wget tar' returned a non-zero code: 1

**Comment by Steven-N-Hart** [comment]
I have this problem at my work sometimes too.  There is some sort of issue with your proxy settings.  Are you using docker-machine?  If so you can just run `eval` on your instance to refresh your IP.
