### ISSUE TITLE
Not able to build the image

### ISSUE THREAD

**Issue by danielnavarrogomez** [Steven-N-Hart/vcf-miner#8]
Hi,

I'm following your steps, after installing docker on my Linux Mint (v17.3) I get and error when I build:

> $ docker build -t vcfminer .
> FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cpusetcpus=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=vcfminer: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

Thanks.

**Comment by Steven-N-Hart** [comment]
Can you verify you have docker configured properly by running `docker run hello-world`

**Comment by danielnavarrogomez** [comment]
My Bad! sorry!
